#! /bin/sh

bspc config border_width 2
bspc config window_gap 9
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#8AD5D1"
bspc config normal_border_color "#76898D"
bspc config focus_follows_pointer true

bspc config wm_name LG3D

bspc desktop HDMI-A-0 -n "main"
bspc monitor HDMI-A-0 -a "web"
bspc monitor HDMI-A-0 -a "edit"
bspc monitor HDMI-A-0 -a "graph"
bspc monitor HDMI-A-0 -a "chrom"
bspc monitor HDMI-A-0 -a "inks"
bspc monitor HDMI-A-0 -a "mail"
bspc monitor HDMI-A-0 -a "devel"
bspc monitor HDMI-A-0 -a "tools"
bspc monitor HDMI-A-0 -a "last"

# Rules
bspc rule -a sublime_text desktop=^3
bspc rule -a Gimp desktop=^4
bspc rule -a Thunderbird desktop=^10
bspc rule -a Firefox desktop=^7
bspc rule -a Chromium desktop=^5
bspc rule -a KeePassX desktop=^11

bspc rule -a File-roller state=floating
bspc rule -a vlc state=floating
bspc rule -a recordMyDesktop state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a xclock state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a mpv state=floating
bspc rule -a Koala state=floating
bspc rule -a Hamster state=floating

$HOME/.config/polybar/launch.sh

setbspwm &
