#! /bin/sh
# FIRST_DESK_MAIN=i
# REMAINING_DESKS_MAIN="ii iii iv v vi vii viii ix x"
# FIRST_DESK_SECONDARY=I
# REMAINING_DESKS_SECONDARY="II III IV V VI VII VIII IX X"

# MONITORS_ASSOCIATED=`bspc query -M | wc -l`

# bspc desktop Desktop01 -n $FIRST_DESK_MAIN
# bspc monitor -a $REMAINING_DESKS_MAIN

# bspc config -m VGA-0 top_padding 14

# bspc monitor -f next

# bspc desktop Desktop02 -n $FIRST_DESK_SECONDARY
# bspc monitor -a $REMAINING_DESKS_SECONDARY

# bspc config -m DVI-1 top_padding 14

.screenlayout/2-lenovo-quadhd-lg-full-hd.sh &

bspc config border_width 2
bspc config window_gap 9
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#8AD5D1"
bspc config normal_border_color "#76898D"
bspc config focus_follows_pointer true

bspc config wm_name LG3D

# Monitor setup
bspc desktop DisplayPort-0 -n "main"
bspc monitor DisplayPort-0 -a "util"
bspc monitor DisplayPort-0 -a "dev"
bspc monitor DisplayPort-0 -a "graph"
bspc monitor DisplayPort-0 -a "virt"

bspc config -m DisplayPort-0  top_padding 14
bspc config -m DisplayPort-0  bottom_padding 14

bspc desktop HDMI-A-0 -n "term"
bspc monitor HDMI-A-0 -a "web"
bspc monitor HDMI-A-0 -a "tool"
bspc monitor HDMI-A-0 -a "pass"
bspc monitor HDMI-A-0 -a "mail"

bspc config -m HDMI-A-0 top_padding 14
bspc config -m HDMI-A-0 bottom_padding 14

# Swap monitors
# bspc monitor HDMI-A-0 -s DisplayPort-0

# move the focus to the main monitor
bspc monitor -f DisplayPort-0

# Rules
bspc rule -a Gimp desktop=^4
bspc rule -a Thunderbird desktop=^0
bspc rule -a Firefox desktop=^7
bspc rule -a Chromium desktop=^8
bspc rule -a KeePassX desktop=^9

bspc rule -a File-roller state=floating
bspc rule -a vlc state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a mpv state=floating

$HOME/.config/polybar/launch.sh

setbspwm &
