#! /bin/sh

# xrandr layout
.screenlayout/1440px2.sh &

bspc config border_width 2
bspc config window_gap 9
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#8AD5D1"
bspc config normal_border_color "#76898D"
bspc config focus_follows_pointer true

bspc config wm_name LG3D

# Monitor setup
# MONITOR01 MONITOR02
bspc desktop DisplayPort-0 -n "main"
bspc monitor DisplayPort-0 -a "util"
bspc monitor DisplayPort-0 -a "dev"
bspc monitor DisplayPort-0 -a "graph"
bspc monitor DisplayPort-0 -a "virt"

bspc config -m DisplayPort-0  top_padding 14
bspc config -m DisplayPort-0  bottom_padding 14

bspc desktop DisplayPort-1 -n "term"
bspc monitor DisplayPort-1 -a "web"
bspc monitor DisplayPort-1 -a "tool"
bspc monitor DisplayPort-1 -a "pass"
bspc monitor DisplayPort-1 -a "mail"

bspc config -m DisplayPort-1 top_padding 14
bspc config -m DisplayPort-1 bottom_padding 14

# Swap monitors
# bspc monitor HDMI-A-0 -s DisplayPort-0

# move the focus to the main monitor
bspc monitor -f DisplayPort-0

# Rules
bspc rule -a Gimp desktop=^4
bspc rule -a Thunderbird desktop=^0
bspc rule -a Firefox desktop=^7
bspc rule -a Chromium desktop=^8
bspc rule -a KeePassX desktop=^9

bspc rule -a File-roller state=floating
bspc rule -a vlc state=floating
bspc rule -a recordMyDesktop state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a xclock state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a mpv state=floating
bspc rule -a Koala state=floating
bspc rule -a Hamster state=floating

${HOME}/bin/setbspwm.sh &
