#! /bin/sh

bspc desktop VGA-0 -n "Web"
bspc monitor VGA-0 -a "Edit"
bspc monitor VGA-0 -a "Mail"
bspc monitor VGA-0 -a "Virtual"
bspc monitor VGA-0 -a "Chromium"

bspc desktop DVI-1 -n "Main"
bspc monitor DVI-1 -a "Pass"
bspc monitor DVI-1 -a "Devel"
bspc monitor DVI-1 -a "Graph"
bspc monitor DVI-1 -a "Vector"
bspc monitor DVI-1 -a "VMachine"

bspc config -m DVI-1 top_padding 14
bspc config -m DVI-1 bottom_padding 14
bspc config -m VGA-0 top_padding 14

# move the focus to the main monitor
bspc monitor -f DVI-1

bspc config border_width 2
bspc config window_gap 48
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#4783BE"
bspc config normal_border_color "#7A6953"
bspc config focus_follows_pointer true

bspc config wm_name LG3D

# Rules
# bspc config rule_command "$(which rule_command)"
#bspwm_rules
bspc rule -a Firefox desktop=^7
bspc rule -a sublime_text desktop=^3
bspc rule -a Gimp desktop=^4 floating=on
bspc rule -a Chromium desktop=^11
bspc rule -a file-roller floating=on
bspc rule -a vlc floating=on
bspc rule -a recordMyDesktop floating=on
bspc rule -a xclock floating=on
bspc rule -a Thunar floating=on

panel &
