#! /bin/sh
# FIRST_DESK_MAIN=i
# REMAINING_DESKS_MAIN="ii iii iv v vi vii viii ix x"
# FIRST_DESK_SECONDARY=I
# REMAINING_DESKS_SECONDARY="II III IV V VI VII VIII IX X"

# MONITORS_ASSOCIATED=`bspc query -M | wc -l`

# bspc desktop Desktop01 -n $FIRST_DESK_MAIN
# bspc monitor -a $REMAINING_DESKS_MAIN

# bspc config -m CRT1 top_padding 14

# bspc monitor -f next

# bspc desktop Desktop02 -n $FIRST_DESK_SECONDARY
# bspc monitor -a $REMAINING_DESKS_SECONDARY

# bspc config -m DFP3 top_padding 14

# Monitor setup
for m in $(bspc query -M); do
        bspc desktop $(bspc query -m $m -D) -n "$m-1"

        for d in $(seq 2 7); do
                bspc monitor $m -a "$m-$d"
        done
done

bspc config -m CRT1 top_padding 14
bspc config -m DFP3 top_padding 14

# move the focus to the main monitor
bspc monitor -f primary

bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config wm_name LG3D

# Rules
bspc config rule_command "xwinfo -cints 0x%X | xargs -d '\n' rulc -t"

rulc -a 'class=="Gimp"' 'desktop=^8 follow=on floating=on'
rulc -a 'class=="Chromium"' 'desktop=^2'
rulc -a 'calss=="pypanel"' 'manage=off'
rulc -a 'instance=="mpv"' 'floating=on'
rulc -a 'class=="Kupfer.py"' 'focus=on'
rulc -a 'class=="Screenkey"' 'manage=off'

# panel bar &
single-panel.sh &

